{
	"version": 1733020731,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/point1-sheet0.png",
		"images/car1-sheet0.png",
		"images/car2-sheet0.png",
		"images/car3-sheet0.png",
		"images/tilemap.png",
		"images/tilemap2.png",
		"images/solids-sheet0.png",
		"images/bonus-sheet0.png",
		"images/confirm.png",
		"images/submitanswer-sheet0.png",
		"images/yes-sheet0.png",
		"images/no-sheet0.png",
		"images/audiologo-sheet0.png",
		"images/audiologo-sheet1.png",
		"images/audiologo-sheet2.png",
		"images/star-sheet0.png",
		"images/health-sheet0.png",
		"images/pointtext.png",
		"images/pausebutton-sheet0.png",
		"images/gameover-sheet0.png",
		"images/bullet-sheet0.png",
		"images/destroy-sheet0.png",
		"images/enemy-sheet0.png",
		"images/enemybullet-sheet0.png",
		"images/enemybullet-sheet1.png",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/player-sheet2.png",
		"images/rocket-sheet0.png",
		"images/rocket-sheet1.png",
		"images/boss-sheet0.png",
		"images/meteorite-sheet0.png",
		"images/explosion2-sheet0.png",
		"images/boss2-sheet0.png",
		"images/enemy2-sheet0.png",
		"images/bossbullet-sheet0.png",
		"images/pillsgreen-sheet0.png",
		"images/bossbullet2-sheet0.png",
		"images/selected-sheet0.png",
		"images/sprite-sheet0.png",
		"images/healthbar-sheet0.png",
		"images/danger-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite2-sheet0.png",
		"media/explosion 1.ogg",
		"media/explosion 2.ogg",
		"media/explosion 3.ogg",
		"media/explosion 4.ogg",
		"media/jetloop1.ogg",
		"media/lazer fire 1.ogg",
		"media/danger alarm meme sound effect [tuberipper.cc].ogg",
		"media/y2mate.com-undertale-ost-068-death-by-glamour.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"question.txt",
		"pathfind.js"
	]
}